name: deploy-update
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: create-deployment
        run: doctl apps create-deployment ${{ secrets.APP_ID }} --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
